name: Install plugins

on:
  workflow_dispatch:
  push:
    branches:
      - test-plugin-install-2

jobs:
  test-action:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
        with:
          ref: test-plugin-install-2
      - uses: ./action
        id: setup-flux
        with:
          version: 3.0.0
          plugins: |
            mirror
      - name: test-plugin
        id: test-plugin
        continue-on-error: true
        run: |
          flux mirror --version
      - name: print outputs
        id: print-output
        env:
          OUTPUT: ${{ steps.setup-flux.outputs.plugin-dir }}
        run: |
          echo $OUTPUT
